version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/loan_pro
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: loan_pro
      MYSQL_USER: loan_pro
      MYSQL_PASSWORD: loan_pro_path
      MYSQL_ROOT_PASSWORD: loan_pro_root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  springapimysql-net:
